---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: podinfo-project-git
  namespace: default
spec:
  type: git
  params:
    - name: url
      value: https://github.com/stefanprodan/podinfo.git
    - name: revision
      value: 2.1.3
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: podinfo-project-image
spec:
  type: image
  params:
    - name: url
      value: 098808187153.dkr.ecr.eu-west-3.amazonaws.com/test/podinfo:2.1.3
